contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
buildDrafts = false
canonifyURLs = true
baseurl = "https://narbais.github.io/Hugo_Aldaketa/"
languageCode = "en-us"
title = "Aldaketa"
# theme
theme = "hugo-now"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-XXXXXX"
sectionPagesMenu = "main"

[[menu.main]]
  name = "This is the post section"
  weight = -110
  identifier = "post"
  url = "/posts/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Le soutien nécessaire dans vos projets"
  author = "Michel Narbais"
  lieu = "Pays-Basque"
  keywords = ["hugo-now", "hugo"]
  avatar = "/img/aldaketa-v2-1.png"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
