baseurl = "http://example.org/"
languageCode = "en-us"
title = "Aldaketa"
# theme
theme = "hugo-now"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-XXXXXX"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Le soutien nécessaire dans vos projets"
  author = "Michel Narbais"
  keywords = ["hugo-now", "hugo"]
  avatar = "/img/aldaketa-v2-1.png"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
